services:


  nginx:
    image: nginx:alpine

    container_name: QueryLens.AI-nginx

    ports:
      - "8000:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - frontend
      - backend

    networks:
      - QueryLens.AI-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: QueryLens.AI-frontend

    expose:
      - "5173"

    networks:
      - QueryLens.AI-network


  backend:
    build:
      context: .
      dockerfile: app/Dockerfile

    container_name: QueryLens.AI-backend

    expose:
      - "8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - QueryLens.AI-network


  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile

    container_name: QueryLens.AI-worker

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    networks:
      - QueryLens.AI-network


  postgres:
    image: postgres:17

    container_name: QueryLens.AI-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: querylens
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 11111

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d querylens"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - QueryLens.AI-network


  redis:
    image: redis:8

    container_name: QueryLens.AI-redis

    restart: unless-stopped

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - QueryLens.AI-network


  rabbitmq:
    image: rabbitmq:4-management

    container_name: QueryLens.AI-rabbitmq

    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 11111

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - QueryLens.AI-network


volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:


networks:
  QueryLens.AI-network:
    driver: bridge