services:

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile

    container_name: experimentos-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    networks:
      - experimentos-network


  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile

    container_name: experimentos-worker

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    networks:
      - experimentos-network


  runner:
    build:
      context: .
      dockerfile: runner/Dockerfile

    container_name: experimentos-runner

    env_file:
      - .env

    networks:
      - experimentos-network


  postgres:
    image: postgres:17

    container_name: experimentos-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: experimentos
      POSTGRES_USER: experimentos
      POSTGRES_PASSWORD: experimentos

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U experimentos -d experimentos"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - experimentos-network


  redis:
    image: redis:8

    container_name: experimentos-redis

    restart: unless-stopped

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - experimentos-network


  rabbitmq:
    image: rabbitmq:4-management

    container_name: experimentos-rabbitmq

    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: experimentos
      RABBITMQ_DEFAULT_PASS: experimentos

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - experimentos-network


volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:


networks:
  experimentos-network:
    driver: bridge